# Generated by Django 4.2.1 on 2023-06-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_birdhouse_color_birdhouse_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdhouse',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='birdhouse',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
